name: Rubocop
on:
  pull_request:  
    types: [opened]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.0.3
      env:
        RAILS_ENV: test

    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Cache bundle gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-${{ env.cache-name }}-
          ${{ runner.os }}-gem-
          ${{ runner.os }}-
    - name: Install Node.js and Yarn
      run: |
        # https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
        curl -sL https://deb.nodesource.com/setup_12.x | bash -
        apt-get install -y nodejs
        # https://classic.yarnpkg.com/en/docs/install#debian-stable
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
        apt update && apt install yarn

    - name: Install Bundler
      run: gem install bundler
    - name: Bundle install
      run: |
        bundle install
      working-directory: ./backend
    - name: Run rubocop
      run: bundle exec bundle exec rubocop
      working-directory: ./backend
