name: Ruby
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup docker build
      shell: bash
      run: |
        docker-compose build
      env:
        RAILS_ENV: test

    - name: Setup docker db:create
      shell: bash
      run: |
        docker-compose run api rails db:create
      env:
        RAILS_ENV: test

    - name: Run RSpec
      shell: bash
      run:  |
        docker-compose run api bundle exec rspec
      env:
        RAILS_ENV: test



      # - uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: 3.0.3

      # - name: Run bundle install
      #   run: |
      #     bundle config --local path vendor/bundle
      #     bundle config --local without production
      #     bundle install

      # - run: RAILS_ENV=test bundle exec rails assets:precompile

      # - run: bundle exec rails rspec

# - name: Setup docker
#       shell: bash
#       run: |
#         # 必要なアップデート
#         docker-compose run app yarn install --check-files
#         docker-compose run app yarn upgrade
#         # イメージのビルド
#         docker-compose build
#         # データベースの作成
#         docker-compose run app rake db:create
#       env:
#         RAILS_ENV: test

#     - name: Run RSpec
#       shell: bash
#       run:  |
#         docker-compose run app bundle exec rspec
#       env:
#         RAILS_ENV: test
