name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3

      - name: Run bundle install
        run: |
          bundle config --local path vendor/bundle
          bundle config --local without production
          bundle install

      - run: RAILS_ENV=test bundle exec rails assets:precompile

      - run: bundle exec rails rspec

  # test:
    # docker:
    #   - image: circleci/ruby:2.7
    #   - image: circleci/mysql:5.5
    #     environment:
    #       MYSQL_ROOT_PASSWORD: "password"
    #       MYSQL_DATABASE: app_test
    #       MYSQL_USER: root
    # environment:
    #   BUNDLE_JOBS: "3"
    #   BUNDLE_RETRY: "3"
    #   APP_DATABASE_HOST: "127.0.0.1"
    #   RAILS_ENV: test
    # working_directory: ~/COVID-Mgr/src
    # steps:
    #   - checkout:
    #       path: ~/COVID-Mgr
    #   - ruby/install-deps
    #   - run:
    #       name: Database setup
    #       command: bundle exec rails db:migrate
    #   - run:
    #       name: test
    #       command: bundle exec rake test
